apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.headlessName }}
  namespace: {{ include "orders-dashboard.namespace" . }}
  labels:
    {{- include "orders-dashboard.labels" . | nindent 4 }}

spec:
  clusterIP: None
  selector:
    {{- include "orders-dashboard.postgresLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}