apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orders-dashboard.secretName" . }}
  namespace: {{ include "orders-dashboard.namespace" . }}
  labels:
    {{- include "orders-dashboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}

  SECRET_KEY: {{ .Values.backend.env.SECRET_KEY | quote }}

  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}

  DATABASE_URL: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ .Values.postgres.service.name }}:{{ .Values.postgres.service.port }}/{{ .Values.postgres.auth.database }}"