apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-dashboard
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/CharanReddy129/orders-dashboard-gitops.git
    targetRevision: main
    path: helm

    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: orders-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true